
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USERAS
 */
public class FeesSystem extends javax.swing.JFrame {

    /**
     * Creates new form FeesSystem
     */
    
     String finame,lname,faname,mname,preaddress,peraddress,conno,regid;
                    Date dateob;
    private Object String;
                    
       public FeesSystem() {
        initComponents();
        
         combox_course.setSelectedItem(null);
         combox_hallname.setSelectedItem(null);
         combox_department.setSelectedItem(null);
         combox_session.setSelectedItem(null);
    }
       
    
        boolean validation()
                {
                   
                    finame=firstname.getText();
                    lname=lastname.getText();
                    faname=fathername.getText();
                    mname=mothername.getText();
                    preaddress=presentaddress.getText();
                    peraddress=permanentaddress.getText();
                    conno=totalcredit.getText();
                    regid=registrationid.getText();
                    dateob=dob.getDate();
                    
                    
                    if(finame.equals(""))
                    { JOptionPane.showMessageDialog(this, "Please Enter First name"); 
                    return false;
                    }
                    if(lname.equals(""))
                    { JOptionPane.showMessageDialog(this, "Please Enter Last name"); 
                    return false;
                    }
                    if(faname.equals(""))
                    { JOptionPane.showMessageDialog(this, "Please Enter Father Name"); 
                    return false;
                    }
                    
                     if(mname.equals(""))
                    { JOptionPane.showMessageDialog(this, "Please Enter Mother Name"); 
                    return false;}
                     
                     if(preaddress.equals(""))
                    { JOptionPane.showMessageDialog(this, "Please Enter Present Address"); 
                    return false;} 
                     
                     if(peraddress.equals(""))
                    { JOptionPane.showMessageDialog(this, "Please Enter Permanent Address"); 
                    return false;} 
                     
                      if(conno.equals(""))
                    { JOptionPane.showMessageDialog(this, "Please Enter Contact no"); 
                    return false;} 
                     
                       if(regid.equals(""))
                    { JOptionPane.showMessageDialog(this, "Please Enter Registration ID"); 
                    return false;} 
                     
                   
                    if(dateob.equals(null))
                    { JOptionPane.showMessageDialog(this, "Please Enter Date of Birth"); 
                    return false;
                    }
                    
             
                 
                    return true;
                }
        
     
         public void checkmobilenumber()
        {
        conno=totalcredit.getText();
        if(conno.length()==10)
        {
            check_lbl_contact.setText(""); }
        else
        {
           check_lbl_contact.setText("Mobile Number should be 10 Digit");
        
        }
        }
         
         
          public void checkregid()
        {
        regid=registrationid.getText();
        if(regid.length()==8)
        {
            check_lbl_regid.setText(""); }
        else
        {
           check_lbl_regid.setText("Must be 8 Digit");
        
        }
        }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        generaterecipt = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        fathername = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        registrationid = new javax.swing.JTextField();
        presentaddress = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        mothername = new javax.swing.JTextField();
        permanentaddress = new javax.swing.JTextField();
        totalcredit = new javax.swing.JTextField();
        combox_semester = new javax.swing.JComboBox<>();
        combox_course = new javax.swing.JComboBox<>();
        dob = new com.toedter.calendar.JDateChooser();
        combox_session = new javax.swing.JComboBox<>();
        combox_department = new javax.swing.JComboBox<>();
        combox_hallname = new javax.swing.JComboBox<>();
        reset1 = new javax.swing.JButton();
        check_lbl_contact = new javax.swing.JLabel();
        check_lbl_regid = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        contactno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        show_course = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        feessystem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1650, 1024));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" First Name :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mother Name :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Father Name :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Semester :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Session :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Course :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hall Name :");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" Present Address :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact No :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Permanent Address :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Registration ID :");

        generaterecipt.setBackground(new java.awt.Color(0, 51, 102));
        generaterecipt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generaterecipt.setForeground(new java.awt.Color(255, 255, 255));
        generaterecipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AllICONS/add2.png"))); // NOI18N
        generaterecipt.setText("Generate Recipt");
        generaterecipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatereciptActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(153, 204, 255));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(153, 204, 255));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AllICONS/printer-.png"))); // NOI18N
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date Of Birth :");

        fathername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fathername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathernameActionPerformed(evt);
            }
        });

        firstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        registrationid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registrationid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationidActionPerformed(evt);
            }
        });
        registrationid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registrationidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                registrationidKeyReleased(evt);
            }
        });

        presentaddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        presentaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentaddressActionPerformed(evt);
            }
        });

        lastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });

        mothername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mothername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothernameActionPerformed(evt);
            }
        });

        permanentaddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        permanentaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permanentaddressActionPerformed(evt);
            }
        });

        totalcredit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalcredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalcreditActionPerformed(evt);
            }
        });
        totalcredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalcreditKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalcreditKeyReleased(evt);
            }
        });

        combox_semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1 Semester 1", "Level 1 Semester 2", "Level 2 Semester 1", "Level 2 Semester 2", "Level 3 Semester 1", "Level 3 Semester 2", "Level 4 Semester 1", "Level 4 Semester 4" }));
        combox_semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_semesterActionPerformed(evt);
            }
        });

        combox_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HUM 1111-Bangladesh Studies-3", "MATH 1111-Linear Algebra and Vector Analysis-3", "PHY 1111-Physics-3", "CSE 1111-Introduction to Computer Systems-3", "CSE 1112-Introduction to Computer Systems Sessional-1.5", "CSE 1121-Structured Programming Language-3", "CSE 1122-Structured Programming Language Sessional-1..5" }));
        combox_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_courseActionPerformed(evt);
            }
        });

        combox_session.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018-2019", "2019-2020", "2020-2021", "2021-2022", "2022-2023" }));
        combox_session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_sessionActionPerformed(evt);
            }
        });

        combox_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science and Engineering", "Electrical and Electronic Engineering", "Mathematics", "Fisheries", "Geology", "Management", "Social Work" }));
        combox_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_departmentActionPerformed(evt);
            }
        });

        combox_hallname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mirza Azam Hall", "Nurunnahar Begum Hall", " " }));
        combox_hallname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_hallnameActionPerformed(evt);
            }
        });

        reset1.setBackground(new java.awt.Color(0, 51, 102));
        reset1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset1.setForeground(new java.awt.Color(255, 255, 255));
        reset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AllICONS/delete.png"))); // NOI18N
        reset1.setText("CLEAR ALL");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });

        check_lbl_contact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        check_lbl_contact.setForeground(new java.awt.Color(204, 0, 51));

        check_lbl_regid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        check_lbl_regid.setForeground(new java.awt.Color(204, 0, 51));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Credit :");

        contactno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });
        contactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactnoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactnoKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        show_course.setColumns(20);
        show_course.setRows(5);
        jScrollPane2.setViewportView(show_course);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(generaterecipt)
                        .addGap(82, 82, 82)
                        .addComponent(reset1)
                        .addGap(87, 87, 87)
                        .addComponent(reset))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(presentaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(check_lbl_regid, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(combox_course, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(combox_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(registrationid, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                                .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(combox_hallname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(jLabel13))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))))))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(mothername, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(permanentaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(combox_department, 0, 1, Short.MAX_VALUE)
                            .addComponent(check_lbl_contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalcredit)
                            .addComponent(combox_session, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contactno, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fathername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mothername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(presentaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permanentaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel13)
                                .addComponent(contactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_lbl_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(registrationid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combox_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_lbl_regid, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(combox_session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combox_hallname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(combox_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(totalcredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(combox_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(reset1)
                                    .addComponent(generaterecipt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1630, 940));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("BSFMSTU  PAYMENT SYSTEM");

        feessystem.setBackground(new java.awt.Color(153, 204, 255));
        feessystem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        feessystem.setForeground(new java.awt.Color(255, 255, 255));
        feessystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AllICONS/home.png"))); // NOI18N
        feessystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feessystemActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1546, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(563, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(342, 342, 342)
                .addComponent(feessystem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(feessystem)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 1660, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
    try
    {
     area.print();
    }
    catch(Exception e)
    {
    }
    }//GEN-LAST:event_resetActionPerformed

    private void generatereciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatereciptActionPerformed
        
        validation();
        area.setText("  \n               Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University        \n");
        area.setText(area.getText()+  "                                              Melandaha,Jamalpur\n");
        area.setText(area.getText()+  "__________________________________________________________________________________________________\n");
        Date obj=new Date(); 
        String Date=obj.toString();
        area.setText(area.getText()+"\nRegistration ID : "+registrationid.getText());
        area.setText(area.getText()+"                                               Date: "+Date+"\n");
        area.setText(area.getText()+  "__________________________________________________________________________________________________\n");
        area.setText(area.getText()+"Student Name:\t"+firstname.getText());
        area.setText(area.getText()+" "+lastname.getText()+"\n");
      
        area.setText(area.getText()+"Father Name:\t"+fathername.getText()+"\n");
        area.setText(area.getText()+"Mother Name:\t"+mothername.getText()+"\n\n");
        area.setText(area.getText()+"Present Address:\t"+presentaddress.getText()+"\n");
        area.setText(area.getText()+"Permanent Address:\t"+permanentaddress.getText()+"\n\n");
        area.setText(area.getText()+"Date of Birth:\t"+dob.getDate()+"\n");
        area.setText(area.getText()+"Contact no:\t"+contactno.getText()+"\n");
        area.setText(area.getText()+  "\n\n__________________________________________________________________________________________________\n");
        String selectedValue1=combox_department.getSelectedItem().toString();
        area.setText(area.getText()+"Department:\t"+selectedValue1+"\n");
        
        String selectedValue2=combox_hallname.getSelectedItem().toString();
        area.setText(area.getText()+"Hall Name:\t"+selectedValue2+"\n");
        
        String selectedValue3=combox_session.getSelectedItem().toString();
        area.setText(area.getText()+"Session:\t"+selectedValue3+"\n");
        
        String selectedValue4=combox_semester.getSelectedItem().toString();
        area.setText(area.getText()+"Semester:\t"+selectedValue4+"\n");
        
        area.setText(area.getText()+"Courses:\n");
        area.setText(area.getText()+  "__________________________________________________________________________________________________\n");
        area.setText(area.getText()+show_course.getText());
        area.setText(area.getText()+  "__________________________________________________________________________________________________\n\n");
      /*  String selectedValue1=combox_course.getSelectedItem().toString();
        String[] result1 = selectedValue1.split("-");
        area.setText(area.getText()+""+result1[0]+"\t"+result1[1]+"-"+result1[2]+"\n");*/
        
        area.setText(area.getText()+"Total Credit:\t"+totalcredit.getText()+"\n");
        String myString = totalcredit.getText();
        int credit = Integer.valueOf(myString);
        int fees=credit*150;
        area.setText(area.getText()+"Total Fees:\t"+fees+"/=\n");
        
    }//GEN-LAST:event_generatereciptActionPerformed

    private void fathernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathernameActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void registrationidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationidActionPerformed

    private void presentaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentaddressActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void mothernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothernameActionPerformed

    private void permanentaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permanentaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permanentaddressActionPerformed

    private void totalcreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalcreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalcreditActionPerformed

    private void combox_semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_semesterActionPerformed
       
        combox_course.setSelectedItem(null);
        
        if(combox_semester.getSelectedItem().equals("Level 1 Semester 1"))
       {   combox_course.removeAllItems();
          
           combox_course.addItem("HUM 1111-Bangladesh Studies-3");
           combox_course.addItem("MATH 1111-Linear Algebra and Vector Analysis-3");
           combox_course.addItem("HUM 1111-PHY 1111-Physics-3");
           combox_course.addItem("CSE 1111-Introduction to Computer Systems-3");
           combox_course.addItem("CSE 1112-Introduction to Computer Systems Sessional-1.5");
           combox_course.addItem("CSE 1121-Structured Programming Language-3");
           combox_course.addItem("CSE 1122-Structured Programming Language Sessional-1.5");
           combox_course.setSelectedItem(null);
       }
            else      
        if(combox_semester.getSelectedItem().equals("Level 1 Semester 2"))
       {
           combox_course.removeAllItems();
           
           combox_course.addItem("HUM 1211-Technical and Communicative English-3");
           combox_course.addItem("HUM 1221-Accounting and Economics for Engineers-3");
           combox_course.addItem("STAT 1211-Statistics for Engineers-3");
           combox_course.addItem("MATH 1211-Differential Calculus, Integral Calculus and Coordinate Geometry-3");
           combox_course.addItem("CSE 1211-Basic Electrical Engineering-3");
           combox_course.addItem("CSE 1212-Basic Electrical Engineering Sessional -1.5");
           combox_course.addItem("CSE 1221-Object Oriented Programming With C++-3");
           combox_course.addItem("CSE 1222-Object Oriented Programming With C++ Sessional-1.5");
           combox_course.setSelectedItem(null);
       }
             
        
        else  
        if(combox_semester.getSelectedItem().equals("Level 2 Semester 1"))
       {
           
           combox_course.removeAllItems();
           
           combox_course.addItem("HUM 2111-Legal Issues and Professional Ethics for Engineers-3");
           combox_course.addItem("MATH 2111-Fourier Analysis, Laplace Transform and Differential equation-3");
           combox_course.addItem("CSE 2111-Cyber and Intellectual Property Law-3");
           combox_course.addItem("CSE 2121-Programming with JAVA-3");
           combox_course.addItem("CSE 2122-Programming with JAVA Sessional-1.5");
           combox_course.addItem("CSE 2131-Basic Electronics-3");
           combox_course.addItem("CSE 2132-Basic Electronics Sessional-1.5");
           combox_course.addItem("CSE 2141-System Analysis and Design-3");
           combox_course.setSelectedItem(null);
       }
      
        else      
        if(combox_semester.getSelectedItem().equals("Level 2 Semester 2"))
       {
           combox_course.removeAllItems();
           
           combox_course.addItem("CSE 2211-Digital Electronics-3");
           combox_course.addItem("CSE 2212-Digital Electronics Sessional-1.5");
           combox_course.addItem("CSE 2221-Data Structure-3");
           combox_course.addItem("CSE 2231-Communication Engineering-3");
           combox_course.addItem("CSE 2232-Communication Engineering Sessional-1.5");
           combox_course.addItem("CSE 2241-Computational Methods for Engineers-3");
           combox_course.addItem("CSE 2251-Digital System Design-3");
           combox_course.addItem("CSE 2252-Digital System Design Sessional-1.5");
           combox_course.setSelectedItem(null);
       }
        else      
        if(combox_semester.getSelectedItem().equals("Level 3 Semester 1"))
       {
           combox_course.removeAllItems();
           
           combox_course.addItem("CSE 3111-Discrete Mathematics-3");
           combox_course.addItem("CSE 3121-Design and Analysis of Algorithm-3");
           combox_course.addItem("CSE 3122-Design and Analysis of Algorithm Sessional-1.5");
           combox_course.addItem("CSE 3131-Operating System and System Programming-3");
           combox_course.addItem("CSE 3132-Operating System and System Programming Sessional-1.5");
           combox_course.addItem("CSE 3141-Database Management System-3");
           combox_course.addItem("CSE 3142-Database Management System Sessiona-3");
           combox_course.addItem("CSE 3151-Computer Architecture and Organization-3");
           combox_course.addItem("CSE 3160-Software Development Project-1.5");
           combox_course.setSelectedItem(null);
       }
        else      
        if(combox_semester.getSelectedItem().equals("Level 3 Semester 2"))
       {
           combox_course.removeAllItems();
           
           combox_course.addItem("CSE 3211-Digital Signal Processing-3");
           combox_course.addItem("CSE 3212-Digital Signal Processing Sessional-1.5");
           combox_course.addItem("CSE 3221-Computer Graphics-3");
           combox_course.addItem("CSE 3222-Computer Graphics Sessional-1.5");
           combox_course.addItem("CSE 3231-Computer Networking-3");
           combox_course.addItem("CSE 3232-Computer Networking Sessional -1.5");
           combox_course.addItem("CSE 3241-Web Engineering-3");
           combox_course.addItem("CSE 3242-Web Engineering Sessional-1.5");
           combox_course.addItem("CSE 3250-Software Development Project-1.5");
           combox_course.setSelectedItem(null);
       }
        else      
        if(combox_semester.getSelectedItem().equals("Level 4 Semester 1"))
       {
           combox_course.removeAllItems();
           
           combox_course.addItem("CSE 4111-Automata Theory and Compiler Design-3");
           combox_course.addItem("CSE 4112-Automata Theory and Compiler Design Sessional-1.5");
           combox_course.addItem("CSE 4121-Microprocessor and Microcontroller-3");
           combox_course.addItem("CSE 4122-Microprocessor and Microcontroller Sessional-1.5");
           combox_course.addItem("CSE 4131-Artificial Intelligence-3");
           combox_course.addItem("CSE 4132-Artificial Intelligence Sessional -1.5");
           combox_course.addItem("Option I (T)Theory:-Should be selected from Table-I-3");
           combox_course.addItem("Option I (S) Sessional:-Based on Option-I (T)-1.5");
           combox_course.addItem("CSE 4180-Thesis/ Project (Part I)-1.5");
           combox_course.setSelectedItem(null);
       }
        else      
        if(combox_semester.getSelectedItem().equals("Level 4 Semester 2"))
       {
           combox_course.removeAllItems();
           
           combox_course.addItem("CSE 4211-Software Engineering-3");
           combox_course.addItem("CSE 4212-Software Engineering Sessional-1.5");
           combox_course.addItem("CSE 4221-Digital Image Processing-3");
           combox_course.addItem("CSE 4222-Digital Image Processing Sessional-1.5");
           combox_course.addItem("Option II (T) Theory:-Should be selected from Table-II-3");
           combox_course.addItem("Option II (S) Sessional:-Based on Option-II (T)-1.5");
           combox_course.addItem("CSE 4270-Industrial Attachment-3");
           combox_course.addItem("CSE 4280-Thesis/ Project (Part II)-3");
           combox_course.addItem("CSE 4290-Board Viva-voce-1.5");
           combox_course.setSelectedItem(null);
       }
           
           
        
      //Level 1 Semester 1, Level 1 Semester 2, Level 2 Semester 1, Level 2 Semester 2, Level 3 Semester 1, Level 3 Semester 2, Level 4 Semester 1, Level 4 Semester 4     
           
           
    }//GEN-LAST:event_combox_semesterActionPerformed

    private void combox_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox_courseActionPerformed

    private void combox_sessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_sessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox_sessionActionPerformed

    private void combox_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox_departmentActionPerformed

    private void combox_hallnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_hallnameActionPerformed
     //combox_hallname.setSelectedItem(null);
    }//GEN-LAST:event_combox_hallnameActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
       area.setText("");
       firstname.setText("");
       lastname.setText("");
       fathername.setText("");
       mothername.setText("");
       presentaddress.setText("");
       permanentaddress.setText("");
       //dob.setDate("");
       totalcredit.setText("");
       registrationid.setText("");
       
       
    }//GEN-LAST:event_reset1ActionPerformed

    private void totalcreditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalcreditKeyPressed
        // TODO add your handling code here:
        checkmobilenumber();
    }//GEN-LAST:event_totalcreditKeyPressed

    private void totalcreditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalcreditKeyReleased
        checkmobilenumber();
    }//GEN-LAST:event_totalcreditKeyReleased

    private void registrationidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrationidKeyPressed
       checkregid();
    }//GEN-LAST:event_registrationidKeyPressed

    private void registrationidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrationidKeyReleased
       checkregid();
    }//GEN-LAST:event_registrationidKeyReleased

    private void feessystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feessystemActionPerformed

        home home=new home();
        home.show();
        this.dispose();
    }//GEN-LAST:event_feessystemActionPerformed

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void contactnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnoKeyPressed
       checkmobilenumber();
    }//GEN-LAST:event_contactnoKeyPressed

    private void contactnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnoKeyReleased
        checkmobilenumber();
    }//GEN-LAST:event_contactnoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
         // String x = combox_course.getSelectedItem().toString();
         // show_course.setText(x);
          
        String selectedValue=combox_course.getSelectedItem().toString();
        String[] result = selectedValue.split("-");
        show_course.setText(show_course.getText()+""+result[0]+"\t"+result[1]+"-"+result[2]+"\n");
        
        
        
                 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void contactnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnoKeyTyped
       checkmobilenumber();
    }//GEN-LAST:event_contactnoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeesSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeesSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea area;
    private javax.swing.JLabel check_lbl_contact;
    private javax.swing.JLabel check_lbl_regid;
    private javax.swing.JComboBox<String> combox_course;
    private javax.swing.JComboBox<String> combox_department;
    private javax.swing.JComboBox<String> combox_hallname;
    private javax.swing.JComboBox<String> combox_semester;
    private javax.swing.JComboBox<String> combox_session;
    private javax.swing.JTextField contactno;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField fathername;
    private javax.swing.JButton feessystem;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton generaterecipt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField mothername;
    private javax.swing.JTextField permanentaddress;
    private javax.swing.JTextField presentaddress;
    private javax.swing.JTextField registrationid;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset1;
    public static javax.swing.JTextArea show_course;
    private javax.swing.JTextField totalcredit;
    // End of variables declaration//GEN-END:variables
}
